# Generated by Django 5.0.1 on 2024-01-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientOwner', models.CharField(max_length=200)),
                ('FirstName', models.CharField(max_length=200, null=True)),
                ('LastName', models.CharField(max_length=200, null=True)),
                ('Patronym', models.CharField(max_length=200, null=True)),
                ('OtherInfo', models.CharField(max_length=200, null=True)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('ClientContact', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
