# Generated by Django 5.0.1 on 2024-01-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lasat_name', models.TextField()),
                ('first_name', models.TextField()),
            ],
        ),
    ]
