# Generated by Django 5.0 on 2023-12-30 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="name",
            new_name="person_name",
        ),
    ]
