# Generated by Django 5.0.1 on 2024-01-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.TextField()),
                ('category', models.TextField()),
            ],
            options={
                'permissions': [('can_change_category', 'Can change category')],
            },
        ),
    ]
