# Generated by Django 5.0 on 2023-12-30 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_menuitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="course",
            new_name="category",
        ),
    ]
