# Generated by Django 5.0 on 2023-12-30 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_rename_course_menuitem_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="name",
            new_name="item_name",
        ),
    ]
